<div class="alert alert-block alert-warning">
    <b>Warning:</b> The content of the note may contain copyrighted material. Do not distribute.
</div>

# Data Structures

Seho Jeong, Sogang University

**References**
- **Coleman, Chase, Spencer Lyon, and Jesse Perla. n.d.** "Introduction to Economic Modeling and Data Science." QuantEcon. https://datascience.quantecon.org/.
- **Sargent, Thomas J., and John Stachurski. n.d.** "Python Programming for Economics and Finance." QuantEcon. https://python-programming.quantecon.org/intro.html.
- **W3 Schools. n.d.** "Python Numbers." W3 School Python Tutorial. https://www.w3schools.com/python/python_numbers.asp.
- **W3 Schools. n.d.** "Python Datetime." W3 School Python Tutorial. https://www.w3schools.com/python/python_datetime.asp.

In this note, we begin with the basics. We learn about core concepts of programming like variables and data structures. We will become familiar with the core data types built into Python, some standard functions we will frequently use, and learn how to define our own functions. By the end, you should have a solid grasp on core Python concepts, be prepared to study the next notes on programming structures and numerical programming, and feel comfortable handling data.

### Contents

1. [Basic Programming Concepts](#basic-programming-concepts)
2. [Strings](#strings)
3. [Numbers, Dates, and Times](#numbers-dates-and-times)
4. [Logical Expressions and Operators](#logical-expressions-and-operators)
5. [Collections](#collections)
6. [Control Flow](#control-flow)

## Basic Programming Concepts

In this section, we will learn some basic concepts of programming and where to search for help.

### Variable Assignment

The very first thing we will learn is the idea of **variable assignment**. Variable assignment associates a value to a variable. Below, we assign the value 'Hello World' to the variable `x`.

In [2]:
x = 'Hello world'

Once we have assigned a value to a variable, Python will remember this variable as long as the current session of Python is still running.

Notice how writing `x` into the prompt below outputs the value 'Hello World'.

In [3]:
x

'Hello world'

However, Python returns an error if we ask it about variables that have not yet been created.

In [4]:
y

NameError: name 'y' is not defined

It is also useful to understand the order in which operations happen. First, the right side of equal sign is computed. Then, that computed value is stored as the variable to the left of the equal sign. For example, what do you think the value of `z` is after running the code below?

In [ ]:
z = 3
z = z + 4
print('z is', z)

Keep in mind that the variable binds a name to a something stored in memory. The name can even be bound to a value of a completely different type.

In [6]:
x = 2
print(x, type(x), id(x))
x = 'something else'
print(x, type(x), id(x))

2 <class 'int'> 4375060272
something else <class 'str'> 4616643952


We now know that when the variable assignment code is executed, Python creates an object of type `int` in your computer's memory, containing the value and some associated attributes. But what is `x` itself in the code above? In Python, `x` is called a name, and the statement `x = 2` binds the name `x` to the integer object we have just discussed.

Under the hood, this process of binding names to objects is implemented as a dictionary &mdash; more about this in a moment.

There is no problem binding two or more names to the one object, regardless of what that object is

In [7]:
a = 31
b = a
id(a) == id(b)

True

In the first step, a `int` object is created, and the name `a` is bound to it. After binding the name `b` to the same object, we can use it anywhere we could use `a`. 

### Variable Names

In Python, variable names must adhere to specific rules for valid syntax and readability.

- Start with a letter or underscore
- Contain only alphanumeric characters and underscores (maybe not!)
- Case-sensitive
- Avoid Python keywords

Also there are some recommended practice for readable codes:

- Use lowercase with underscores (snake_case) (e.g., `total_price`)
- Be descriptive
- Constants in uppercase (e.g., `API_KEYS`)

#### Other Topics

### Code Comments

Comments are short notes that you leave for yourself and for others who read your code. They should be used to explain what the code does. A comment is made with the `#`. Python ignores everything in a line that follows a `#`.

Let's practice making some comments.

In [8]:
i = 1 # Assign the value 1 to variable i
j = 2 # Assign the value 2 to variable j

# We add i and j below this line.
i + j

3

### Built-In Functions

Functions are processes that take an input(s) and produce an output. If we had a function called `f` that took two arguments `x` and `y`, we would write `f(x, y)` to use the function. For example, the function `print` simply prints whatever it is given. recall the variable we created called `x`.

In [9]:
print(x)

something else


### Getting Help

We can figure out what a function does by asking for help. In Jupyter notebooks, this is done by placing a `?` after the function name (without paranthesis) and evaluating the cell. For example, we can ask for help on the `print()` function by writing `print?`.

In [10]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

Now, practice by yourself. Read about what the `len` function does (by writing `len?`). What will it produce if we give it the variable `x`? Check whether you were right by running the code `len(x)`.

In [18]:
# Your answers here!

### Objects and Types

#### Objects

Everything in Python is an **object**. Objects are things that contain (1) data and (2) functions that can operate on the data. Sometimes we refer to the functions inside an object as **methods**. We can investigate what data is inside an object and which methods it supports by typing after `.` after that particular variable, then hitting `TAB`. You can scroll down this list by using the up and down arrows. We often refer to this as "tab completion" or "introspection".

#### Types

We often want to identify what kind of object some value is– called its “type”. A **type** is an abstraction which defines a set of behavior for any “instance” of that type ,i.e., `2.0` and `3.0` are instances of float, where float has a set of particular common behaviors.

In particular, the type determines:
- the available data for any “instance” of the type (where each instance may have different values of the data).
- the methods that can be applied on the object and its data.

We can figure this out by using the `type()` function. The `type()` function takes a single argument and outputs the type of that argument.



In [13]:
type(3)

int

In [14]:
type('Hello World')

str

In [15]:
type([1, 2, 3])

list

We will learn more about each of types (and others!) and how to use them soon, so stay tuned!

### Modules

Python takes a **modular approach** to tools. By this we mean that sets of related tools are bundled together into *packages*. (You may also hear the term modules to describe the same thing.)

For example:
- `pandas` is a package that implements the tools necessary to do scalable data analysis.
- `matplotlib` is a package that implements visualization tools.
- `requests` and `urllib` are packages that allow Python to interface with the internet.

As we move further into the class, being able to access these packages will become very important. We can bring a package’s functionality into our current Python session by writing


```python
import package
```

Once we have done this, any function or object from that package can be accessed by using `package.name`. Here’s an example.

In [17]:
import sys  # for dealing with your computer's system
sys.version # information about the Python version in use

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:22:19) [Clang 14.0.6 ]'

We can use our introspection skills to investigate a package's contents. In the cell below, use the tab completion to find a function from the `time` module that will display the local time. Use `time.FUNC_NAME?` (where `FUNC_NAME` is replaced with the function you found) to see information about that function and then call the function. (*Hint.* Look for something to do with the word `local`.)

In [19]:
import time
# Your answers here!

#### Module Aliases

Some packages have long names (see `matplotlib`, for example) which makes accessing the package functionality somewhat inconvenient. To ease this burden, Python allows us to give aliases or “nicknames” to packages.

For example we can write:
```python
import package as p
```

This statement allows us to access the packages functionality as `p.function_name` rather than `package.function_name`. Some common aliases for packages are
- `import pandas as pd`
- `import numpy as np`
- `import matplotlib as mpl`
- `import datetime as dt`

While you can choose any name for an alias, we suggest that you stick to the common ones. You will learn what these common ones are over time.



Try running `import time as t` in the cell below, then see if you can call the function you identified above. Does it work?

In [ ]:
import time as t

### Good Code Habits

A common saying in the software engineering world is:

> Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. **Code for readability.**

This might be a dramatic take, but the most important feature of your code after correctness is readability. We encourage you to do everything in your power to make your code as readable as possible. Here are some suggestions for how to do so:

- Comment frequently. Leaving short notes not only will help others who use your code, but will also help you interpret your code after some time has passed.
- Anytime you use a comma, place a space immediately afterwards.
- Whitespace is your friend. Don’t write line after line of code – use blank lines to break it up.
- Don’t let your lines run too long. Some people reading your code will be on a laptop, so you want to ensure that they don’t need to scroll horizontally and right to read your code. We recommend no more than 80 characters per line.

## Numbers, Dates, and Times

### Integers, Floating Point Numbers, Complex Numbers

Python has two types of numbers.

- Integer (`int`): These can only take the values of the integers i.e. $\{\cdots, -2, -1, 0, 1, 2, \cdots\}$
- Floating Point Number (float): Think of these as any real number such as $1.0$, $3.1415$, or $-100.022358\cdots$.

The easiest way to differentiate these types of numbers is to find a decimal place after the number. A float will have a decimal place, but an integer will not.

Below, we assign integers to the variables `xi` and `zi` and assign floating point numbers to the variables `xf` and `zf`.

In [63]:
xi = 1
xf = 1.0
zi = 123
zf = 1230.5    # Notice -- There are no commas!
zf2 = 1_230.5  # If needed, we use `_` to separate numbers for readability

Create the following variables:

- `D`: A floating point number with the value 10,000
- `r`: A floating point number with value 0.025
- `T`: An integer with value 30

We will use them in a later exercise.

In [64]:
# Your answers here.

### Python as a Calculator

You can use Python to perform mathematical calculations.

In [66]:
a = 4
b = 2

print("a + b is", a + b)
print("a - b is", a - b)
print("a * b is", a * b)
print("a / b is", a / b)
print("a ** b is", a ** b)
print("a ^ b is", a ^ b)

a + b is 6
a - b is 2
a * b is 8
a / b is 2.0
a ** b is 16
a ^ b is 6


You likely could have guessed all except the last two. Note that Python uses `**`, not `^` for exponentation (raising a number to a power)! 

Notice also that above `+`, `-` and `**` all returned an integer type, but `/` converted the result to a float. When possible, operations between integers return an integer type. 

All operations involving a float will result in a float.

In [67]:
a = 4
b = 2.0

print("a + b is", a + b)
print("a - b is", a - b)
print("a * b is", a * b)
print("a / b is", a / b)
print("a ** b is", a**b)

a + b is 6.0
a - b is 2.0
a * b is 8.0
a / b is 2.0
a ** b is 16.0


We can also chain together operations.

When doing this, Python follows the standard order of operations &mdash; parenthesis, exponents, multiplication and division, followed by addition and subtraction.

For example,

In [68]:
x = 2.0
y = 3.0
z1 = x + y * x
z2 = (x + y) * x

What do you think `z1` is? How about `z2`?

Remember the variables we created earlier? Let’s compute the present discounted value of a payment ($D$) made in $T$ years assuming an interest rate of 2.5%. Save this value to a new variable called `PDV` and print your output. 

The formula is $$\text{PDV} = \frac{D}{(1+r)^T}.$$

In [ ]:
# Your answers here!

### Other Math Functions

We often want to use other math functions on our numbers. Let’s try to calculate sin(2.5).

In [69]:
sin(2.5)

NameError: name 'sin' is not defined

As seen above, Python complains that `sin` isn’t defined. The problem here is that the `sin` function &mdash; as well as many other standard math functions &mdash; are contained in the math package.

We must begin by importing the `math` package.

In [70]:
import math

Now, we can use `math.[TAB]` to see what functions are available to us.

In [71]:
# Found math.sin()
math.sin(2.5)

0.5984721441039564

Use the `math` package to compute the value of $e^3 + 4^e$.

In [75]:
# Your answers here.

Verify the “trick” where the percent difference ($\frac{x - y}{y}$) between two numbers close to 1 can be well approximated by the difference between the log of the two numbers ($\log(x) - \log(y)$).

Use the numbers `x` and `y` below.

In [76]:
x = 1.05
y = 1.02

# Your answers here.

Execute `math.factorial?` to discover what `math.factorial()` does and what argument are needed.

In [77]:
# Your answers here.

You can also express infinity with Python.

In [78]:
math.inf

inf

Or you can also express a data numerical although it is not. 

In [79]:
math.nan

nan

### Floor/Modulus Division Operators

You are less likely to run into the following operators, but understanding that they exist is useful. For two numbers assigned to the variables `x` and `y`,
- Floor division: `x // y`
- Modulus division: `x % y`

Remember when you first learned how to do division and you were asked to talk about the quotient and the remainder? That’s what these operators correspond to…

Floor division returns the number of times the divisor goes into the dividend (the quotient) and modulus division returns the remainder.

An example would be 37 divided by 7:
- Floor division would return 5 (7 * 5 = 35)
- Modulus division would return 2 (2 + 35 = 37)

Try it!

In [73]:
37 // 7

5

In [74]:
37 % 7

2

Predict the results by looking at the following code.

In [ ]:
1 / math.inf

In [ ]:
math.inf * 2

In [ ]:
math.inf / math.inf

### Complex Numbers

Complex numbers are written with a `j` as the imaginary part.

In [82]:
x = 3+5j
y = 5j
z = -5j

print(x, type(x))
print(y, type(y))
print(z, type(z))

(3+5j) <class 'complex'>
5j <class 'complex'>
(-0-5j) <class 'complex'>


### Type Conversion

You can convert from one type to another with the `int()`, `float()`, and `complex()` methods.

In [81]:
x = 1    # int
y = 2.8  # float
z = 1j   # complex

# Convert from int to float:
a = float(x)

# Convert from float to int:
b = int(y)

# Convert from int to complex:
c = complex(x)

print(a)
print(b)
print(c)

print(type(a))
print(type(b))
print(type(c))

1.0
2
(1+0j)
<class 'float'>
<class 'int'>
<class 'complex'>


### Dates and Times

A date in Python is not a data type of its own, but we can import a module named `datetime` to work with dates as date objects.

Import the datetime module and display the current date:

In [80]:
import datetime

x = datetime.datetime.now()
print(x)

2025-07-27 23:56:56.769508


When we execute the code from the example above the result will be: `2025-07-28 00:14:26.151795`. The date contains year, month, day, hour, minute, second, and microsecond.

The datetime module has many methods to return information about the date object. Here are a few examples, you will learn more about them later in Day 4. 

Return the year and name of weekday:

In [83]:
x = datetime.datetime.now()

print(x.year)
print(x.strftime("%A"))

2025
Monday


To create a date, we can use the `datetime()` class (constructor) of the `datetime` module. The `datetime()` class requires three parameters to create a date: year, month, day.

In [84]:
x = datetime.datetime(2020, 5, 17)
print(x)

2020-05-17 00:00:00


The `datetime()` class also takes parameters for time and timezone (hour, minute, second, microsecond, tzone), but they are optional, and has a default value of `0`, (`None` for timezone).

The `datetime` object has a method for formatting date objects into readable strings. The method is called `strftime()`, and takes one parameter, `format`, to specify the format of the returned string:

In [85]:
x = datetime.datetime(2018, 6, 1)
print(x.strftime("%B"))

June


## Strings

### Generating a String

**Textual information** is stored in a data type called a **string(문자열)**. To denote that you would like something to be stored as a string, you **place it inside of quotation marks**.For example, you can write
```python
"this is a string"    # Notice the quotation marks
'this is a string'    # Notice the quotation marks
this is not a string  # No quotation marks
```

You can use either `"` or `'` to create a string. Just make sure that you **start and end the string with the same one**! Notice that if we ask Python to tell us the type of a string, it abbreviates its answer to `str`.

In [20]:
type("this is a string")

str

The code below is invalid Python code
```python
x = 'What's wrong with this string'
```
How can you fix it?

In [21]:
# Your answers here.

### String Operations

Some of arithmetic operators we saw in the numbers section also work on strings:

- Put two strings together: `x + y`
- Repeat the string `x` a total of `n` times: `n * x` (or `x * n`)

In [22]:
x = 'Hello'
y = 'World'

In [23]:
x + y

'HelloWorld'

In [24]:
3 * x

'HelloHelloHello'

What happens if we try `*` with two strings, or `-` or `/`? The best way to find out is to try it!

In [25]:
a = '1'
b = '2'

a * b

TypeError: can't multiply sequence by non-int of type 'str'

In [26]:
a - b

TypeError: unsupported operand type(s) for -: 'str' and 'str'

Now using the variables `x` and `y`, how could you create the sentence `Hello World`? (*Hint.* Think about how to present space as a string.)

In [27]:
# Your answers here!

### String Methods

We can use many methods to manipulate strings. We will not be able to cover all of them here, but let's take a look at some of the most useful ones.

In [28]:
x

'Hello'

In [29]:
x.lower() # Makes all letters lowercase

'hello'

In [30]:
x.upper() # Makes all letters uppercase

'HELLO'

In [31]:
x.count('l') # Counts number of a particular string

2

In [32]:
x.count('ll')

1

In [33]:
z = ' Hello'
z.strip() # Remove leading and trailing whitespace.

'Hello'

One of our facorite (and most frequently used) string methods is `replace()`. It substitutes all occurrences of a particular pattern with a different pattern. For the variable `test` below, use the `replace` method to change the `c` to a `d`. (*Hint.* Type `test.replace?` to get some help for how to use the method replace.)

In [34]:
test = 'abc'
# Your answers here!

Suppose you are working with price data and encounter the value `'$6.50'`. We recognize this as being a number representing the quantity "six dollars and fifty cents". However, Python interprets the value as the string `'$6.50'`. Here, your task is to convert the variable `price` below into a number.

In [35]:
price = '$6.50'

# Your answers here!

### String Formatting

Sometimes we’d like to reuse some portion of a string repeatedly, but still make some relatively small changes at each usage. We can do this with **string formatting**, which done by using `{}` as a placeholder where we’d like to change the string, with a variable name or expression.

Let’s look at an example.

In [36]:
country = "Vietnam"
GDP = 223.9
year = 2017
my_string = f"{country} had ${GDP} billion GDP in {year}"
print(my_string)

Vietnam had $223.9 billion GDP in 2017


Rather than just substituting a variable name, you can use a calculation or expression.

In [37]:
print(f"{5}**2 = {5**2}")

5**2 = 25


Or, using our previous example

In [38]:
my_string = f"{country} had ${GDP * 1_000_000} GDP in {year}"
print(my_string)

Vietnam had $223900000.0 GDP in 2017


In these cases, the `f` in front of the string causes Python interpolate any valid expression within the `{}` braces.

Now, lookup a country in [World Bank database](https://data.worldbank.org/), and format a string showing the growth rate of GDP over the last 2 years.

In [39]:
# Your answers here

Alternatively, to reuse a formatted string, you can call the `format` method (noting that you do **not** put f in front).

In [40]:
gdp_string = "{country} had ${GDP} billion in {year}"
gdp_string.format(country = "Vietnam", GDP = 223.9, year = 2017)

'Vietnam had $223.9 billion in 2017'

Let's practice! Instead of hard-coding the values above, try to use the `country`, `GDP` and `year` variables you previously defined.

In [41]:
# Your answers here.

Create a new string and **use formatting** to produce each of the following statements
- “The 1st quarter revenue was 110M”
- “The 2nd quarter revenue was 95M”
- “The 3rd quarter revenue was 100M”
- “The 4th quarter revenue was 130M”

In [43]:
# Your answers here.

## Logical Expressions and Operators

### Logical Expressions

A **logical expression** is a statement that can either be **true or false**. For example, 'a < b' is a logical expression. It can be true or false depending on what values of a and b are given.

Note that this differs from a **mathematical expression** which denotes a truth statement. In the previous example, the mathematical expression 'a < b' means that a is less than b, and values of a and b where a ≥ b are not permitted.

Logical expressions form the basis of computing, so for the purposes of this book, **all statements are assumed to be logical rather than mathematical** unless otherwise indicated.

### Booleans

In Python, a logical expression that is true will compute to the value `True`. A false expression will compute to the value `False`. This is a new data type we come across &mdash; **boolean**, which has the built-in values `True` and `False`.

For the purpose of this note, **“True” is equivalent to 1**, and **“False” is equivalent to 0**. Distinguishing between the numbers 1 and 0 and the logical values “True” and “False” is beyond the scope of this book, but it is covered in more advanced books on computing.

Logical expressions are used to pose questions to Python.
- For example, “3 < 4” is equivalent to, “Is 3 less than 4?”
- Since this statement is true, Python will compute it as 1.
- However, "3 > 4" is false, therefore Python will compute it as 0.

Let’s start by creating some booleans and looking at them.

In [44]:
x = True
y = False

type(x)

bool

In [45]:
x

True

In [46]:
y

False

### Comparison Operators

**Comparison operators** compare the value of two numbers, and they are used to build logical expressions. Python reserves the symbols `>`, `>=`, `<`, `<=`, `!=`, `==`, to denote “greater than”, “greater than or equal”, “less than”, “less than or equal”, “not equal”, and “equal”, respectively.

Let’s start with an example `a = 4`, `b = 2`, and see the following table:

<center>

| Operator | Meanings | Example | Output |
| --- | --- | --- | --- |
| == | equal | `a == b` | `False` |
| != | not equal | `a != b` | `True` |
| > | greater than | `a > b` | `True` |
| >= | greater than or equal | `a >= b` | `True` |
| < | less than | `a < b` | `False` |
| <= | less than or equal | `a <= b` | `False` |

</center>

We demonstrate this as below:

In [47]:
a = 4
b = 2

print("a > b", "is", a > b)
print("a < b", "is", a < b)
print("a == b", "is", a == b)
print("a >= b", "is", a >= b)
print("a <= b", "is", a <= b)

a > b is True
a < b is False
a == b is False
a >= b is True
a <= b is False


### Logical Operators

**Logical operators** are operations between two logical expressions that, for the sake of discussion, we call P and Q. The fundamental logical operators we will use herein are **and**, **or**, and **not**.

The **truth table** of a logical operator or expression gives the result of every truth combination of P and Q. The truth tables for “and”, “or”, and “not” are given in the following figure.

<center>

| P | Q | P and Q | P or Q | not P |
| --- | --- | --- | --- | --- |
| True | True | True | True | False |
| True | False | False | True | False |
| False | True | False | True | True |
| False | False | False | False | True |

</center>

Occasionally, **determining whether a statement is “not true” or “not false” is more convenient than simply “true” or “false”***. This is known as **negating** a statement. In Python, we can negate a boolean using the word `not`.

In [48]:
not False

True

In [49]:
not True

False

#### Multiple Comparisons: Conjunction `and` and Disjunction `or`

Sometimes we need to evaluate multiple comparisons at once. This is done by using the words `and` and `or`.

However, these are the “mathematical” *and*s and *or*s – so they don’t carry the same meaning as you’d use them in colloquial English.
- `a and b` is true only when **both** `a` and `b` are true.
- `a or b` is true whenever **at least one** of `a` or `b` is true.

For example,
- The statement “I will accept the new job if the salary is higher *and* I receive more vacation days” means that you would only accept the new job if you both receive a higher salary and are given more vacation days.
- The statement “I will accept the new job if the salary is higher *or* I receive more vacation days” means that you would accept the job if (1) they raised your salary, (2) you are given more vacation days, or (3) they raise your salary and give you more vacation days.

Let’s see some examples.

In [50]:
True and True

True

In [51]:
True and False

False

In [52]:
False or True

True

In [53]:
False or False

False

Just as with arithmetic operators, logical operators have an **order of operations** relative to each other and in relation to arithmetic operators. **All arithmetic operations will be executed before comparison operations**, which will be **executed before logical operations**. 

**Parentheses** can be used to change the order of operations.

In [54]:
1 + 3 > 2 + 5

False

Even when the order of operations is known, it is usually **helpful for you and those reading your code to use parentheses to make your intentions clearer**. In the preceding example `(1 + 3) > (2 + 5)` is clearer.

In Python’s implementation of logic, 1 is used to denote true and 0 for false. However, 1 and 0 are still numbers. Therefore, Python will allow abuses such as: (3 > 2) + (5 > 4), which will resolve to 2.

In [55]:
(3 > 2) + (5 > 4)

2

Although in formal logic, 1 is used to denote true and 0 to denote false, Python slightly abuses notation and it will take any number not equal to 0 to mean true when used in a logical operation. For example, 3 and 1 will compute to true.

Do not utilize this feature of Python. **Always use 1 to denote a true statement**.

Let's practice now! Without typing the commands, determine whether the following statements are true or false. Once you have evaluated whether the command is `True` or `False`, run the code in Python.

In [ ]:
x = 2
y = 2
z = 4

# Statement 1
x > z

# Statement 1
x == y

# Statement 3
(x < y) and (x > y)

# Statement 4
(x < y) or (x > y)

# Statement 5
(x <= y) and (x >= y)

# Statement 6
True and ((x < z) or (x < y))

### Quantifiers

We have seen how we can use the words `and` and `or` to process two booleans at a time. The functions `all` and `any` allow us to process an unlimited number of booleans at once.

#### Universal Quantifiers

Let $P_1$, $P_2$, $P_3$, $\cdots$, $P_n$ be statements where we can determine either it is true or false. Then `all([P_1, P_2, ⋯, P_n])` is equivalent to `P_1 and P_2 and ⋯ and P_n`. That is, `all(bools)` will return `True` if and only if all the booleans in `bools` is `True` and returns `False` otherwise.

In [56]:
all([True, True, True])

True

In [57]:
all([False, True, False])

False

In [58]:
all([False, False, False])

False

For now, do not worry about what the `[` and `]` mean – they allow us to create lists which we will learn about in an upcoming lecture.

#### Existential Quantifier

Let $P_1, P_2, P_3, \cdots, P_n$ be statements where we can determine either it is true or false. Then `any([P_1, P_2, ⋯, P_n])` is equivalent to `P_1 or P_2 or P_2 or ⋯ or P_n`. That is, `any(bools)` returns `True` whenever one or more of `bools` is `True`.

In [59]:
any([True, True, True])

True

In [60]:
any([False, True, False])

True

In [61]:
any([False, False, False])

False

## Collections

### Ordered Collections

#### Lists

A Python `list` is an **ordered collection of items**. We can create lists using the following syntax:
```python
[item1, item2, ⋯, itemN]
```
Each item can be of any type.

Let’s create some lists.

In [86]:
# created, but not assigned to a variable
[2.0, 9.1, 12.5]

[2.0, 9.1, 12.5]

In [87]:
# stored as the variable `x`
x = [2.0, 9.1, 12.5]
print('x has type', type(x))
x

x has type <class 'list'>


[2.0, 9.1, 12.5]

#### What can we do with lists?

We can **access items in a list** called `mylist` using `mylist[N]` where `N` is an integer(`int`). Anytime that we use the syntax `x[i]` we are doing what is called **indexing** – it means that we are **selecting a particular element of a collection** `x`.

In [88]:
x[1]

9.1

Wait? Why did `x[1]` return `9.1` when the first element in x is actually `2.0`? This happened because Python starts counting at zero! Lets repeat that one more time for emphasis **Python starts counting at zero!** 

To access the first element of x we must use `x[0]`:

In [89]:
x[0]

2.0

We can also determine **how many items are in a list** using the `len()` function.

In [90]:
len(x)

3

What happens if we try to index with a number higher than the number of items in a list?

In [91]:
x[4]

IndexError: list index out of range

We can check **if a list contains an element** using the `in` keyword.

In [92]:
2.0 in x

True

In [93]:
1.5 in x

False

For our list x, there are other common operations we might want to do.

In [94]:
x.reverse()
x

[12.5, 9.1, 2.0]

In [96]:
number_list = [10, 25, 42, 1.0]
print(number_list)

number_list.sort() # Sort elements in ascending or descending manner.
print(number_list)

[10, 25, 42, 1.0]
[1.0, 10, 25, 42]


Note that in order to sort, we had to have all elements in our list be numbers (`int` and `float`), more on this below. We could actually do the same with a list of strings. In this case, sort will put the items in alphabetical order.

In [97]:
str_list = ["NY", "AZ", "TX"]
print(str_list)

str_list.sort()
print(str_list)

['NY', 'AZ', 'TX']
['AZ', 'NY', 'TX']


The `append` method **adds an element to the end of existing list**.

In [98]:
num_list = [10, 25, 42, 8]
print(num_list)

num_list.append(10)
print(num_list)

[10, 25, 42, 8]
[10, 25, 42, 8, 10]


However, if you call `append` with a list, it adds a `list` to the end, rather than the numbers in that list.

In [99]:
num_list = [10, 25, 42, 8]
print(num_list)

num_list.append([20, 4]) # 리스트 속 원소가 아닌 리스트 자를 원소로서 추가한다.
print(num_list)

[10, 25, 42, 8]
[10, 25, 42, 8, [20, 4]]


To combine the lists instead…

In [100]:
num_list = [10, 25, 42, 8]
print(num_list)
num_list.extend([20, 4])
print(num_list)

[10, 25, 42, 8]
[10, 25, 42, 8, 20, 4]


Let's practice! In the first cell, try `y.append(z)`.In the second cell try `y.extend(z)`. Explain the behavior.

In [101]:
y = ["a", "b", "c"]
z = [1, 2, 3]

# Your answers here.

print(y)

['a', 'b', 'c']


In [102]:
y = ["a", "b", "c"]
z = [1, 2, 3]

# Your answers here.

print(y)

['a', 'b', 'c']


#### Lists of Different Types

While most examples above have all used a `list` with a single type of variable, this is not required. Let’s carefully make a small change to the first example: replace `2.0` with `2`

In [103]:
x = [2, 9.1, 12.5]

This behavior is identical for many operations you might apply to a list. Below we have also introduced a new module, Numpy, which provides many functions for working with numeric data.

In [104]:
import numpy as np

x = [2, 9.1, 12.5]

np.mean(x) == sum(x)/len(x)

True

Taking this further, we can **put completely different types of elements** inside of a list.

In [105]:
# stored as the variable `x`
x = [2, "hello", 3.0]
print("x has type", type(x))
x

x has type <class 'list'>


[2, 'hello', 3.0]

To see the types of individual elements in the list:

In [106]:
print(f"type(x[0]) = {type(x[0])}, type(x[1]) = {type(x[1])}, type(x[2]) = {type(x[2])}")

type(x[0]) = <class 'int'>, type(x[1]) = <class 'str'>, type(x[2]) = <class 'float'>


While no programming limitations prevent this, you should be **careful if you write code with different numeric and non-numeric types in the same list**.
- For example, if the types within the list cannot be compared, then how could you sort the elements of the list?
- i.e. How do you determine whether the string “hello” is less than the integer 2, “hello” < 2?

In [107]:
x = [2, "hello", 3.0]
x.sort()

TypeError: '<' not supported between instances of 'str' and 'int'

A few key exceptions to this general rule are:
- Lists with **both integers and floating points are less error-prone**(since mathematical code using the list would work with both types).
- When working with lists and data, you may want to **represent missing values with a different type than the existing values**.

#### The `range` Function

One function you will see often in Python is the `range` function.
It has three versions:
1. `range(N)`: goes from 0 to N-1
2. `range(a, N)`: goes from a to N-1
3. `range(a, N, d)`: goes from a to N-1, counting by d

When we call the `range` function, we get back something that has type `range:

In [108]:
r = range(5)
print("type(r)", type(r))

type(r) <class 'range'>


To turn the range into a list:

In [109]:
list(r)

[0, 1, 2, 3, 4]

In [110]:
# try list(range(a, N)) -- you pick `a` and `N`


In [111]:
# try list(range(a, N, d)) -- you pick `a`, `N`, and `d`


Let's practice! Experiment with the other two versions of the `range` function.

#### Tuples

Tuples are very similar to lists and hold ordered collections of items. However, tuples and lists have three main differences:
1. Tuples are created using parenthesis — `(` and `)` — instead of square brackets — `[` and `]`.
2. Tuples are **immutable**, which is a fancy computer science word meaning that **they can’t be changed or altered after they are created**.
3. Tuples and multiple return values from functions are tightly connected, as we will see in functions. 

In [112]:
t = (1, "hello", 3.0)
print("t is a", type(t))
t

t is a <class 'tuple'>


(1, 'hello', 3.0)

We can convert a list to a tuple by calling the `tuple` function on a list.

In [113]:
print("x is a", type(x))
print("tuple(x) is a", type(tuple(x)))
tuple(x)

x is a <class 'list'>
tuple(x) is a <class 'tuple'>


(2, 'hello', 3.0)

We can also convert a tuple to a list using the `list` function.

In [114]:
list(t)

[1, 'hello', 3.0]

As with a list, we access items in a tuple `t` using `t[N]` where N is an int.

In [115]:
t[0]  # still start counting at 0

1

In [116]:
t[2]

3.0

Verify that tuples are indeed immutable by attempting the following:
- Changing the first element of `t` to be 100
- Appending a new element `"!!"` to the end of `t` (remember with a list `x` we would use `x.append("!!")` to do this)
- Sorting `t`
- Reversing `t`

In [ ]:
# change first element of t

In [ ]:
# appending to t

In [ ]:
# sorting t

In [117]:
# reversing t

#### Lists vs. Tuples

Should you use a list or tuple? This depends on what you are storing, whether you might **need to reorder the elements**, or **whether you’d add new elements without a complete reinterpretation of the underlying data**. 

For example, take data representing the GDP (in trillions) and population (in billions) for China in 2015.

In [118]:
china_data_2015 = ("China", 2015, 11.06, 1.371)
print(china_data_2015)

('China', 2015, 11.06, 1.371)


In this case, we have used a tuple since:
- (a) ordering would be meaningless; and
- (b) adding more data would require a reinterpretation of the whole data structure.

On the other hand, consider a list of GDP in China between 2013 and 2015.

In [119]:
gdp_data = [9.607, 10.48, 11.06]
print(gdp_data)

[9.607, 10.48, 11.06]


In this case, we have used a list, since adding on a new element to the end of the list for GDP in 2016 would make complete sense. Along these lines, collecting data on China for different years may make sense as a list of tuples (e.g. year, GDP, and population – although we will see better ways to store this sort of data in the Pandas section).

In [120]:
china_data = [(2015, 11.06, 1.371), (2014, 10.48, 1.364), (2013, 9.607, 1.357)]
print(china_data)

[(2015, 11.06, 1.371), (2014, 10.48, 1.364), (2013, 9.607, 1.357)]


In general, a rule of thumb is to use a list unless you need to use a tuple. Key criteria for tuple use are when you want to:
- ensure **the order of elements can’t change**
- ensure **the actual values of the elements can’t change**
- **use the collection as a key in a `dict`** (we will learn what this means soon)

#### `zip` and `enumerate`

Two functions that can be extremely useful are `zip` and `enumerate`. Both of these functions are best understood by example, so let’s see them in action and then talk about what they do.

In [121]:
gdp_data = [9.607, 10.48, 11.06]
years = [2013, 2014, 2015]
z = zip(years, gdp_data)
print("type(z)", type(z))

type(z) <class 'zip'>


To see what is inside `z`, let’s convert it to a list.

In [122]:
list(z)

[(2013, 9.607), (2014, 10.48), (2015, 11.06)]

Notice that we now have a list where each item is a tuple. Within each tuple, we have one item from each of the collections we passed to the `zip` function. In particular, the first item in z contains the first item from `[2013, 2014, 2015]` and the first item from `[9.607, 10.48, 11.06]`. The second item in `z` contains the second item from each collection and so on.

We can **access an element in this** and then **unpack the resulting tuple directly into variables**.

In [123]:
l = list(zip(years, gdp_data))
x, y = l[0] # unpack the first element of `l`
print(f"year = {x}, GDP = {y}")

year = 2013, GDP = 9.607


Now let’s experiment with `enumerate`.

In [124]:
e = enumerate(["a", "b", "c"])
print("type(e)", type(e))
e

type(e) <class 'enumerate'>


Again, we call `list(e)` to see what is inside.

In [125]:
list(e)

[(0, 'a'), (1, 'b'), (2, 'c')]

We again have a list of tuples, but this time, **the first element in each tuple is the index of the second tuple element in the initial collection**. Notice that the third item is `(2, 'c')` because `["a", "b", "c"][2]` is `'c'`

For the tuple `foo` below, use a combination of `zip`, `range`, and `len` to mimic `enumerate(foo)`. Verify that your proposed solution is correct by converting each to a list and checking equality with `==`.

In [126]:
foo = ("good", "luck!")
# Your answers here!

An important quirk of some iterable types that are not lists (such as the above `zip`) is that you cannot convert the same type to a list twice. This is because `zip`, `enumerate`, and `range` produce what is called a **generator**.

A generator will **only produce each of its elements a single time**, so if you **call list on the same generator a second time**, it will not have any elements to iterate over anymore. For more information, refer to the [Python documentation](https://docs.python.org/3/howto/functional.html#generators).

In [127]:
gdp_data = [9.607, 10.48, 11.06]
years = [2013, 2014, 2015]

z = zip(years, gdp_data)

l = list(z)
print(l)

m = list(z)
print(m)

[(2013, 9.607), (2014, 10.48), (2015, 11.06)]
[]


### Associative Collections

#### Dictionaries

A **dictionary (or dict)** associates `key`s with `value`s. It will feel similar to a dictionary for words, where the keys are words and the values are the associated definitions. 

The most common way to create a `dict` is to use curly braces — `{` and `}` — like this:
```python
{"key1": value1, "key2": value2, ..., "keyN": valueN}
```

The crucial part of the syntax is that **each key-value pair is written `key: value`** and that **these pairs are separated by commas — `,`**. Let’s see an example using our aggregate data on China in 2015.

In [128]:
china_data = {"country": "China", "year": 2015, "GDP" : 11.06, "population": 1.371}
print(china_data)

{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371}


Unlike our above example using a `tuple`, a `dict` allows us to associate a name with each field, rather than having to remember the order within the tuple. Often, code that makes a dict is easier to read if we put each `key: value` pair on its own line. (Recall our earlier comment on using whitespace effectively to improve readability!)

The code below is equivalent to what we saw above.

In [129]:
china_data = {
    "country": "China",
    "year": 2015,
    "GDP" : 11.06,
    "population": 1.371
}

Most often, the keys (e.g. “country”, “year”, “GDP”, and “population”) will be strings, but we could also use numbers (`int`, or `float`) or even `tuple`s(or, rarely, a combination of types). The values can be **any** type and **different** from each other.

Create a new dict which associates stock tickers(주식종목코드) with its stock price.
Here are some tickers and a price.
- AAPL: 175.96
- GOOGL: 1047.43
- TVIX: 8.38

In [130]:
# Your answers here!

This next example is meant to emphasize how values can be anything – including another dictionary.

In [131]:
companies = {"AAPL": {"bid": 175.96, "ask": 175.98},
             "GE": {"bid": 1047.03, "ask": 1048.40},
             "TVIX": {"bid": 8.38, "ask": 8.40}}
print(companies)

{'AAPL': {'bid': 175.96, 'ask': 175.98}, 'GE': {'bid': 1047.03, 'ask': 1048.4}, 'TVIX': {'bid': 8.38, 'ask': 8.4}}


#### Getting, Setting, and Updating `dict` items

We can now ask Python to tell us the value for a particular key by using the syntax `d[k]`, where `d` is our `dict` and `k` is the key for which we want to find the value. For example,

In [132]:
print(china_data["year"])
print(f"country = {china_data['country']}, population = {china_data['population']}")

2015
country = China, population = 1.371


When inside of a formatting string, you can use `'` instead of `"` as above to ensure the formatting still works with the embedded code. If we ask for the value of a key that is not in the dict, we will get an error.

In [133]:
china_data["inflation"]

KeyError: 'inflation'

We can also **add new items to a dict** using the syntax `d[new_key] = new_value`. Let’s see some examples.

In [134]:
print(china_data)
china_data["unemployment"] = "4.05%"
print(china_data)

{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371}
{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371, 'unemployment': '4.05%'}


To **update the value**, we use assignment in the same way (which will create the key and value as required).

In [135]:
print(china_data)
china_data["unemployment"] = "4.051%"
print(china_data)

{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371, 'unemployment': '4.05%'}
{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371, 'unemployment': '4.051%'}


Or we could **change the type**.

In [136]:
china_data["unemployment"] = 4.051
print(china_data)

{'country': 'China', 'year': 2015, 'GDP': 11.06, 'population': 1.371, 'unemployment': 4.051}


Look at [the World Factbook for Australia](https://www.cia.gov/the-world-factbook/countries/australia/) and create a dictionary with data containing the following types: float, string, integer, list, and dict. Choose any data you wish. To confirm, you should have a dictionary that you identified via a key.

In [137]:
# Your answers here!

#### Common `dict` Functionality

We can do some common things with dicts. We will demonstrate them with examples below.

In [138]:
# number of key-value pairs in a dict
len(china_data)

5

In [139]:
# Get a list of all the keys.
list(china_data.keys())

['country', 'year', 'GDP', 'population', 'unemployment']

In [140]:
# Get a list of all the values
list(china_data.values())

['China', 2015, 11.06, 1.371, 4.051]

In [ ]:
more_china_data = {"irrigated_land": 690_070, "top_religions": {"buddhist": 18.2, "christian" : 5.1, "muslim": 1.8}}

# Add all key-value pairs in mydict2 to mydict.
# If the key already appears in mydict, overwrite the value with the value in mydict2
china_data.update(more_china_data)
china_data

{'country': 'China',
 'year': 2015,
 'GDP': 11.06,
 'population': 1.371,
 'unemployment': 4.051,
 'irrigated_land': 690070,
 'top_religions': {'buddhist': 18.2, 'christian': 5.1, 'muslim': 1.8}}

In [142]:
# Get the value associated with a key or return a default value.
# Use this to avoid the NameError we saw above if you have a reasonable efault value.
china_data.get("irrigated_land", "Data Not Available")

690070

In [143]:
china_data.get("death_rate", "Data Not Available") # print "Data Not Available" if there is no key named "death_rate"

'Data Not Available'

Use Jupyter’s help facilities to learn how to use the `pop` method to remove the key `"irrigated_land"` (and its value) from the dict.

In [146]:
# Your answers here.

Explain what happens to the value you popped. Experiment with calling `pop` twice.

In [147]:
# Your answers here.

### Sets

Python has an additional way to represent collections of items: **sets**. Sets come up infrequently, but you should be aware of them. 

If you are familiar with the mathematical concept of sets, then you will understand the majority of Python sets already. If you don’t know the math behind sets, don’t worry: we’ll cover the basics of Python’s sets here.

A set is **an unordered collection of unique elements**. The syntax for creating a set uses curly bracket `{` and `}`.
```python
{item1, item2, ..., itemN}
```

Here is an example

In [148]:
s = {1, "hello", 3.0}
print("s has type", type(s))
s

s has type <class 'set'>


{1, 3.0, 'hello'}

Try creating a set with repeated elements (e.g. {1, 2, 1, 2, 1, 2}). What happens? Why?

In [149]:
# Your answers here.

As with lists and tuples, we can check if something is in the set and check the set’s length:

In [150]:
print("len(s) =", len(s))
"hello" in s

len(s) = 3


True

Unlike lists and tuples, we can’t extract elements of a set `s` using `s[N]` where N is a number.

In [151]:
s[1]

TypeError: 'set' object is not subscriptable

This is because sets are **not ordered**, so the notion of getting the second element (`s[1]`) is not well defined.

We add elements to a set `s` using `s.add`.

In [152]:
s.add(100)
s

{1, 100, 3.0, 'hello'}

In [153]:
s.add("hello") # nothing happens, why?
s

{1, 100, 3.0, 'hello'}

We can also do **set operations**. Consider the set s from above and the set s2 = {"hello", "world"}.
- `s.union(s2)`: returns a set with all elements in either s or s2 (합집합)
- `s.intersection(s2)`: returns a set with all elements in both s and s2 (교집합)
- `s.difference(s2)`: returns a set with all elements in s that aren’t in s2 (차집합)
- `s.symmetric_difference(s2)`: returns a set with all elements in only one of s and s2 (대칭차집합)

Test out two of the operations described above using the original set we created, `s`, and the set created below `s2`.

In [154]:
s2 = {"hello", "world"}

In [155]:
# Operation 1; Please write your code here!

In [156]:
# Operation 2; Please write your code here!

As with tuples and lists, a set function can convert other collections to sets.

In [157]:
x = [1, 2, 3, 1]
set(x)

{1, 2, 3}

In [158]:
t = (1, 2, 3, 1)
set(t)

{1, 2, 3}

Likewise, we can convert sets to lists and tuples.

In [159]:
list(s)

[1, 'hello', 3.0, 100]

In [160]:
tuple(s)

(1, 'hello', 3.0, 100)

### Other Useful Collections

[Namedtuple](https://www.geeksforgeeks.org/python/namedtuple-in-python/)

## Control Flow

### Net Preset Values and Asset Pricing

In **`6.3`**, we’ll introduce two related topics from economics:
- Net present valuations
- Asset pricing

These topics will motivate some of the programming we do in following sections.

#### Discount Rate

In economics and finance, **“assets” provide a stream of payoffs**. These “assets” can be concrete or abstract:
- a stock pays dividends over time,
- a bond pays interest,
- an apple tree provides apples,
- a job pays wages, and
- an education provides possible jobs (which, in turn, pay wages).
When **deciding the price to pay for an asset** or how to choose between different alternatives, we need to take into account that **most people would prefer to receive 1 today vs. 1 next year.** This reflection on consumer preferences leads to the notion of a **discount rate(할인율)**. If you are indifferent between receiving 1.00 today and 1.10 next year, then the discount rate over the next year is $r = 0.10$ (=10%).

If we assume that an individuals preferences are consistent over time, then we can apply that same discount rate to valuing assets further into the future.
- For example, we would expect that the consumer would be indifferent between consuming 1.00 today and $(1+r)(1+r)=1.21$ dollars two years from now (i.e. discount twice).

Inverting this formula, 1 delivered two years from now is equivalent to $\frac{1}{(1+r)^2}$ today. (2년 후의 1의 가치와 현재의 $\frac{1}{(1+r)^2}$의 가치가 동일하다.)

Government bonds are often issued as **zero-coupon bonds(무이표채)**, meaning that they make no payments throughout the entire time that they are held, but, rather make a single payment at the time of maturity. How much should you be willing to pay for a zero-coupon bond that paid 100 in 10 years with an interest rate of 5%?

In [162]:
# Your answers here.

#### Net Present Value

If an asset pays a stream of payoffs over multiple time periods, then we can use a discount rate to calculate the value to the consumer of a entire sequence of payoffs. Most generally, we enumerate each discrete time period (e.g. year, month, day) by the index $t$ where today is $t=0$ and the asset lives for $T$ periods.

List the payoff at each time period as $y_t$, which we will assume, for now, is known in advance. Then if the discount factor is $r \ge 0$, the consumer “values” the payoff $y_t$ delivered at time $t$ as $\frac{1}{(1+r)^t}y_t$ where we note that if
$t = 0$, the value is just the current payoff $y_0$.

Using this logic, we can write an expression for the value of the entire sequence of payoffs with a sum. $$ P_0 = \sum^{T}_{t=0} \left( \frac{1}{1+r} \right)^t y_t \tag{1}$$

If $y_t$ is a constant, then we can compute this sum with a simple formula! Below, we present some useful formulas that come from infinite series that we will use to get our net present value formula. ($y_t$가 상수이면 $y_t$가 시그마 밖으로 빠져나가게 되고, 결국 등비급수의 합을 구하는 문제가 된다.) For any constant $0 < \beta < 1$ and integer value $\tau > 0$,

$$ \sum^{∞}_{t=0} \beta^t = \frac{1}{1-\beta} $$

$$ \sum^{\tau}_{t=0} \beta^t = \frac{1-\beta^{\tau+1}}{1-\beta} \tag{2}$$

$$ \sum^{∞}_{t=\tau} \beta^t = \frac{\beta^{\tau}}{1-\beta} $$

In the case of an asset which pays one dollar until time $T$, we can use these formulas, taking $\beta = \frac{1}{1+r}$ and $T=\tau$, to find

$$ P_0 = \sum^{\tau}_{t=0} \left( \frac{1}{1+r} \right)^t = \frac{1-(\frac{1}{1+r})^{\tau+1}}{1-\frac{1}{1+r}} = \frac{1+r}{r} - \frac{1}{r} \left(\frac{1}{1+r}\right)^{\tau} $$

Note that we can also consider an asset that lives and pays forever if $T=\infty$, and from (2), the value of an asset which pays 1 forever is $\frac{1+r}{r}$.

### Conditionals

#### `if` or `if-else`

Sometimes, we will only want to execute some piece of code if a certain condition is met. These conditions can be anything.
- For example, we might add to total sales if the transaction value is positive, but add to total returns if the value is negative.
- Or, we might want to add up all incurred costs, only if the transaction happened before a certain date.

We use conditionals **to run particular pieces of code when certain criterion are met**. (즉 **조건(condition)이 참일 때 그 아래 코드조각을 실행한다.**) **Conditionals are closely tied to booleans**, so if you don’t remember what those are, go back to **`3`** for a refresher. The basic syntax for conditionals is
```python
if condition:
    # code to run when condition is True
else:
    # code to run if no conditions above are True
```

Note that immediately following the condition, **there is a colon(`:`)** and that the next line begins with blank spaces (which are called indentation). **Using 4 spaces is a very strong convention for indentation**, so that is what we do — we recommend that you do the same. Also note that the `else` clause is optional.

Let’s see some simple examples.

In [163]:
if True:
    print("This is where `True` code is run")

This is where `True` code is run


The example below is equivalent to just typing the print statement.

In [ ]:
if 1 < 2:
    print("This is where `True` code is run")

This is where `True` code is run


Now, it is not equivalent to just typing the print statement.

In [ ]:
if False:
    print("This is where `True` code is run") 

In [166]:
if 1 > 2:
    print("This is where `True` code is run")

Notice that when you run the cells above nothing is printed. That is because **the condition for the if statement was not true, so the code inside the indented block was never run.** This also allows us to demonstrate the role of indentation in determining the “block” of code.

In [167]:
val = False

if val is True: # check an expression
    print("This is where `True` code is run")
    print("More code in the if block")
print("Code runs after 'if' block, regardless of val") 

Code runs after 'if' block, regardless of val


Run the following two variations on the code with only a single change in the indentation. After, modify the `x` to print `3` and then `2`, `3` instead.

In [169]:
x = 1

if x > 0:
    print("1")
    print("2")
print("3")

1
2
3


In [170]:
x = 1

if x > 0:
    print("1")
print("2") # changed the indentation
print("3")

1
2
3


The next example shows us how `else` works.

In [171]:
val = (2 == 4)  # returns False

if val is True:
    print("This is where `True` code is run")
else:
    print("This is where `False` code is run")
    print("More else code")

print("Code runs after 'if' block, regardless of val")

This is where `False` code is run
More else code
Code runs after 'if' block, regardless of val


The `if False: ...` part of this example is the same as the example before, but now, we added an `else:` clause. In this case, **because the conditional for the `if` statement was not `True`, the if code block was not executed, but the `else` block was.** Finally, the `Condition is True` is assumed in the `if` statement, and is often left out.

For example, the following are identical:

In [172]:
if (1 < 2) is True:
    print("1 < 2")

if 1 < 2:
    print("1 < 2")

1 < 2
1 < 2


Using the code cell below as a start, print `"Good afternoon"` if the `current_time` is past noon. Otherwise, do nothing. (*Hint.* Write some conditional based on `current_time.hour`.)

In [174]:
import datetime
current_time = datetime.datetime.now()

# Your answers here!

In this example, you will generate a random number between 0 and 1 and then display “x > 0.5” or “x < 0.5” depending on the value of the number. This also introduces a new package `numpy.random` for drawing random numbers.

In [175]:
import numpy as np
x = np.random.random() # 0부터 1 사이의 난수 하나를 `x`에 할당합니다.
print(f"x = {x}")

# Your answers here.

x = 0.08575712006944569


#### `if-elif-else` Statement

Sometimes, you have more than one condition you want to check.
- For example, you might want to run a different set of code based on which quarter a particular transaction took place in.
- In this case you could check whether the date is in Q1(1분기), or in Q2(2분기), or in Q3(3분기), or if not any of these it must be in Q4(4분기).

The way to express this type of conditional is to use one or more `elif` clause in addition to the `if` and the `else`.

The syntax is:
```python
if condition1:
    # code to run when condition1 is True
elif condition2:
    # code to run when condition2 is True
elif condition3:
    # code to run when condition3 is True
else:
    # code to run when none of the above are true
```

You can **include as many `elif` clauses as you want**. As before, the **`else` part is optional**. Here’s how we might express the quarter example referred to above.

In [176]:
import datetime
halloween = datetime.date(2017, 10, 31) # 할로윈 날짜를 변수에 할당합니다.

if halloween.month > 9:
    print("Halloween is in Q4")
elif halloween.month > 6:
    print("Halloween is in Q3")
elif halloween.month > 3:
    print("Halloween is in Q2")
else:
    print("Halloween is in Q1")

Halloween is in Q4


Note that when there are multiple `if` or `elif` conditions, **only the code corresponding to the first true clause is run**. (가장 먼저 조건이 참인 코드블럭만 실행 후 해당 `if-elif-else` 문의 나머지 코드블럭은 무시하고 넘어간다.) We saw this in action above.
- We know that when `halloween.month > 9` is true, then **`halloween.month > 6` and `alloween.month > 3` must also be true, but only the code block associated with `halloween.month > 9` was printed.**

### Iterations

When doing computations or analyzing data, we often need to **repeat certain operations a finite number of times** or **until some condition is met**. Examples include:
- processing all data files in a directory (folder),
- aggregating revenues and costs for every period in a year, or
- computing the net present value of certain assets.

These are all examples of a programming concept called **iteration**. We feel the concept is best understood through example, so we will present a contrived example and then discuss the details behind doing iteration in Python.

#### A Contrived Example

Suppose we wanted to print out the first 10 integers and their squares. We could do something like this.

In [178]:
print(f"1**2 = {1**2}")
print(f"2**2 = {2**2}")
print(f"3**2 = {3**2}")
print(f"4**2 = {4**2}")
# .. and so on until 10

1**2 = 1
2**2 = 4
3**2 = 9
4**2 = 16


As you can see, the code above is repetitive. For each integer, the code is exactly the same except for the two places where the “current” integer appears.

Suppose that I asked you to write the same print statement for an int stored in a variable named `i`. You might write the following code:
```python
print(f"{i}**2 = {i**2}")
```

This more general version of the operation suggests a strategy for achieving our goal with less repetition of code:
- have a variable `i` take on the values 1 through 10 (Quiz: How can we use `range` to create the numbers 1 to 10? Answer: `range(1, 11)`) and run the line of code above for each new value of i.

This can be accomplished with a `for` loop!

In [179]:
for i in range(1, 11):
     print(f"{i}**2 = {i**2}")

1**2 = 1
2**2 = 4
3**2 = 9
4**2 = 16
5**2 = 25
6**2 = 36
7**2 = 49
8**2 = 64
9**2 = 81
10**2 = 100


Whoa😮, what just happened? The integer `i` took on the values in `range(1, 11)` one by one and for each new value it did the operations in the indented block (here just one line that called the `print` function).

#### `for` Loops

The general structure of a standard `for` loop is as follows.
```python
for item in iterable:
        # operation 1 with item
        # operation 2 with item
        # ...
        # operation N with item
```

`iterable` is anything capable of producing one item at a time (see [here](https://docs.python.org/3/glossary.html#term-iterable) for official definition from the Python team). We’ve actually already seen some of the most common iterables!
- Lists, tuples, dicts, and range/zip/enumerate objects are all iterables.

Note that we can have as many operations as we want inside the indented block. We will **refer to the indented block as the “body” of the loop.** **When the for loop is executed, `item` will take on one value from `iterable` at a time and execute the loop body for each value.**

In economics, when **an individual has some knowledge, skills, or education which provides them with a source of future income**, we call it [human capital](https://en.wikipedia.org/wiki/Human_capital).

When a student graduating from high school is considering whether to continue with post-secondary education, they may consider that it gives them higher paying jobs in the future, but requires that they don’t begin working until after graduation. Consider the simplified example where a student has perfectly forecastable employment and is given two choices:
1. Begin working immediately and make 40,000 a year until they retire 40 years later.
2. Pay 5,000 a year for the next 4 years to attend university, then get a job paying 50,000 a year until they retire 40 years after making the college attendance decision.

Should the student enroll in school if the discount rate is $r = 0.05$?

In [180]:
# Discount rate
r = 0.05

# High school wage
w_hs = 40_000

# College wage and cost of college
c_college = 5_000
w_college = 50_000

# Compute npv of being a hs worker; Please write your code here!


# Compute npv of attending college; Please write your code here!


# Compute npv of being a college worker; Please write your code here!


# Is npv_collegeworker - npv_collegecost > npv_hsworker; Please write your code here!



When iterating, each `item` in `iterable` might actually contain more than one value. Recall that tuples (and lists) can be unpacked directly into variables.

In [181]:
tup = (4, "test")
i, x = tup
print(f"i = {i}, x = {x}, tup = {tup}")

i = 4, x = test, tup = (4, 'test')


Also, recall that the value of a `enumerate(iterable)` is a tuple of the form `(i, x)` where `iterable[i] == x`. When we use `enumerate` in a for loop, we can “unpack” both values at the same time as follows:

In [182]:
# revenue by quarter
company_revenue = [5.12, 5.20, 5.50, 6.50]

for index, value in enumerate(company_revenue):
    print(f"quarter {index} revenue is ${value} million")

quarter 0 revenue is $5.12 million
quarter 1 revenue is $5.2 million
quarter 2 revenue is $5.5 million
quarter 3 revenue is $6.5 million


Similarly, the index can be used to access another vector.

In [183]:
cities = ["Phoenix", "Austin", "San Diego", "New York"]
states = ["Arizona", "Texas", "California", "New York"]

for index, city in enumerate(cities):
    state = states[index]
    print(f"{city} is in {state}")

Phoenix is in Arizona
Austin is in Texas
San Diego is in California
New York is in New York


Instead of the above, write a for loop that uses the lists of cities and states below to print the same “{city} is in {state}” using a `zip()` instead of an `enumerate()`.

In [184]:
cities = ["Phoenix", "Austin", "San Diego", "New York"]
states = ["Arizona", "Texas", "California", "New York"]

# Please write your code here!

#### `while` Loops

A related but slightly different form of iteration is to **repeat something until some condition is met.** This is typically achieved using a `while` loop.

The structure of a while loop is:
```python
while True_condition:
    # repeat these steps
```

`True_condition` is some conditional statement that should **evaluate to True when iterations should continue and False when Python should stop iterating**. For example, suppose we wanted to know the smallest N such that $\sum\limits^N_{i=0}i > 1000$.

We figure this out using a while loop as follows.

In [185]:
total = 0
i = 0
while total <= 1000:
    i = i + 1
    total = total + i

print("The answer is", i)

The answer is 45


Let’s check our work. 

In [186]:
# Should be just less than 1000 because range(45) goes from 0 to 44
sum(range(45))

990

In [187]:
# should be between 990 + 45 = 1035
sum(range(46))

1035

A warning: one common programming error with while loops is to forget to **set the variable you use in the condition prior to executing**. For example, take the following code which correctly sets a counter.

In [188]:
i = 0

And then executes a while loop

In [189]:
while i < 3:
    print(i)
    i = i + 1
print("done")

0
1
2
done


No problems. But if you were to execute the above cell again, or another cell, the `i = 3` remains, and code is never executed (since `i < 3` begins as False).

Companies often invest in training their employees to raise their productivity. Economists sometimes wonder why companies spend this money when this incentivizes other companies to hire their employees away with higher salaries since employees gain human capital from training?

Let’s say that it costs a company 25,000 dollars to teach their employees Python, but it raises their output by 2,500 per month. How many months would an employee need to stay for the company to find it profitable to pay for their employees to learn Python if their discount rate is r = 0.01?

In [190]:
# Define cost of teaching python
cost = 25_000
r = 0.01

# Per month value
added_value = 2500

n_months = 0
total_npv = 0.0

# Put condition below here: 아래를 잘보고 코드를 수정해주세요.
while False: # (replace False with your condition here)
    n_months = n_months + 1  # Increment how many months they've worked

    # Increase total_npv

#### `break` and `continue`

Sometimes we want to stop a loop early if some condition is met. Let’s revisit the example of finding the smallest N such that $\sum\limits^N_{i=0}i > 1000$.

Clearly `N` must be less than 1000, so we know we will find the answer if we start with a for loop over all items in `range(1001)`. Then, we can keep a running total as we proceed and tell Python to stop iterating through our range once total goes above 1000.

In [191]:
total = 0
for i in range(1001):
    total = total + i
    if total > 1000:
        break

print("The answer is", i)

The answer is 45


Try to find the index of the first value in `x` that is greater than 0.999 using a for loop and `break`. (*Hint.* Try iterating over range(len(x)).)

In [192]:
x = np.random.rand(10_000)
# Your answers here.

Sometimes we might want to **stop the body of a loop early if a condition is met.** To do this we can use the `continue` keyword. The basic syntax for doing this is:
```python
for item in iterable:
      # always do these operations
      if condition:
          continue

      # only do these operations if condition is False
```

Inside the loop body, Python will **stop that loop iteration of the loop and continue directly to the next iteration** when it encounters the `continue ` statement. For example, suppose I ask you to loop over the numbers 1 to 10 and print out the message “{i} An odd number!” whenever the number `i` is odd, and do nothing otherwise.

You can use `continue` to do this as follows:

In [193]:
for i in range(1, 11):
    if i % 2 == 0:  # an even number... This is modulus division
        continue

    print(i, "is an odd number!")

1 is an odd number!
3 is an odd number!
5 is an odd number!
7 is an odd number!
9 is an odd number!


Write a for loop that adds up all values in `x` that are greater than or equal to 0.5. Use the `continue` word to end the body of the loop early for all values of `x` that are less than 0.5. (*Hint.* Try starting your loop with for value in `x`: instead of iterating over the indices of `x`.)

In [194]:
x = np.random.rand(10_000)
# Write your answers here.

#### Comprehension

Often, we will want to **perform a very simple operation for every element of some iterable** and **create a new iterable** with these values. This could be done by writing a for loop and saving each value, but often using what is called a **comprehension** is more readable. 

Like many Python concepts, a comprehension is easiest to understand through example. Imagine that we have a list `x` with a list of numbers.
- We would like to create a list `x2` which has the squared values of `x`.

In [195]:
x = list(range(4)) # a list of numbers

# [Solution 1] Create squared values with a loop
x2_loop = []
for x_val in x:
    x2_loop.append(x_val**2)

# [Solution 2] Create squared values with a comprehension
x2_comp = [x_val**2 for x_val in x]

print(x2_loop)
print(x2_comp)

[0, 1, 4, 9]
[0, 1, 4, 9]


Notice that much of the same text appears when we do the operation in the loop and when we do the operation with the comprehension. We need to specify what we are iterating over – in both cases, this is for `x_val` in `x`. We need to square each element `x_val**2`. It needs to be stored somewhere – **(Solution 1)** in `x2_loop`, this is done by appending each element to a list, and **(Solution 2)** in x2_comp, this is done automatically because the operation is enclosed in a list. 

**We can do comprehension with many different types of iterables**, so we demonstrate a few more below.

Create a dictionary with tickers for keys and corresponding stock price for values.

In [196]:
# Create a dictionary from lists
tickers = ["AAPL", "GOOGL", "TVIX"]
prices = [175.96, 1047.43, 8.38]

d = {key: value for key, value in zip(tickers, prices)}
d

{'AAPL': 175.96, 'GOOGL': 1047.43, 'TVIX': 8.38}

Define a list that contains HQ addresses from the dictionary.

In [197]:
# Create a list from a dictionary
d = {"AMZN": "Seattle", "TVIX": "Zurich", "AAPL": "Cupertino"}

hq_cities = [d[ticker] for ticker in d.keys()]
hq_cities

['Seattle', 'Zurich', 'Cupertino']

Create a list of values of sine functions with arguments from 0 to 10.

In [198]:
import math

# List from list
x = range(10)

sin_x = [math.sin(x_val) for x_val in x]
sin_x

[0.0,
 0.8414709848078965,
 0.9092974268256817,
 0.1411200080598672,
 -0.7568024953079283,
 -0.9589242746631385,
 -0.27941549819892586,
 0.6569865987187891,
 0.9893582466233818,
 0.4121184852417566]

Returning to our previous example: print “{city} is in {state}” for each combination using a `zip` and a comprehension.

In [199]:
cities = ["Phoenix", "Austin", "San Diego", "New York"]
states = ["Arizona", "Texas", "California", "New York"]

# Please write your code here

Finally, we can use this approach to build complicated nested dictionaries.

In [201]:
gdp_data = [9.607, 10.48, 11.06]
years = [2013, 2014, 2015]
exports = [ {"manufacturing": 2.4, "agriculture": 1.5, "services": 0.5},
            {"manufacturing": 2.5, "agriculture": 1.4, "services": 0.9},
            {"manufacturing": 2.7, "agriculture": 1.4, "services": 1.5}]

# Merge data defined above.
data = zip(years, gdp_data,exports)
data_dict = {year : {"gdp" : gdp, "exports": exports} for year, gdp, exports in data} # comprehension
print(data_dict)

# total exports by year
[data_dict[year]["exports"]["services"] for year in data_dict.keys()]

{2013: {'gdp': 9.607, 'exports': {'manufacturing': 2.4, 'agriculture': 1.5, 'services': 0.5}}, 2014: {'gdp': 10.48, 'exports': {'manufacturing': 2.5, 'agriculture': 1.4, 'services': 0.9}}, 2015: {'gdp': 11.06, 'exports': {'manufacturing': 2.7, 'agriculture': 1.4, 'services': 1.5}}}


[0.5, 0.9, 1.5]

This is it for Day 1! See you tomorrow. Don't forget to review the notes!